function DataConverter(c){this.nodeId=c;this.node=$("#"+c);this.outputDataTypes=[{text:"Actionscript",id:"as",notes:""},{text:"ASP/VBScript",id:"asp",notes:""},{text:"HTML",id:"html",notes:""},{text:"JSON - Properties",id:"json",notes:""},{text:"JSON - Column Arrays",id:"jsonArrayCols",notes:""},{text:"JSON - Row Arrays",id:"jsonArrayRows",notes:""},{text:"MySQL",id:"mysql",notes:""},{text:"PHP",id:"php",notes:""},{text:"Python - Dict",id:"python",notes:""},{text:"Ruby",id:"ruby",notes:""},{text:"XML - Properties",
id:"xmlProperties",notes:""},{text:"XML - Nodes",id:"xml",notes:""}];this.outputDataType="xml";this.columnDelimiter="\t";this.rowDelimiter="\n";this.inputTextArea={};this.outputTextArea={};this.inputHeader={};this.outputHeader={};this.dataSelect={};this.outputText=this.inputText="";this.newLine="\n";this.indent="  ";this.commentLine="//";this.commentLineEnd="";this.tableName="MrDataConverter";this.downcaseHeaders=this.headersProvided=this.useUnderscores=true;this.upcaseHeaders=false;this.includeWhiteSpace=
true;this.useTabsForIndent=false}
DataConverter.prototype.create=function(c,i){var b=this;this.inputHeader=$('<div class="groupHeader" id="inputHeader"><p class="groupHeadline">Input CSV or tab-delimited data. <span class="subhead"> Using Excel? Simply copy and paste. No data on hand? <a href="#" id="insertSample">Use sample</a></span></p></div>');this.inputTextArea=$('<textarea class="textInputs" id="dataInput"></textarea>');for(var a='<div class="groupHeader" id="inputHeader"><p class="groupHeadline">Output as <select name="Data Types" id="dataSelector" >',e=
0;e<this.outputDataTypes.length;e++)a+='<option value="'+this.outputDataTypes[e].id+'" '+(this.outputDataTypes[e].id==this.outputDataType?'selected="selected"':"")+">"+this.outputDataTypes[e].text+"</option>";a+='</select><span class="subhead" id="outputNotes"></span></p></div>';this.outputHeader=$(a);this.outputTextArea=$('<textarea class="textInputs" id="dataOutput"></textarea>');this.node.append(this.inputHeader);this.node.append(this.inputTextArea);this.node.append(this.outputHeader);this.node.append(this.outputTextArea);
this.dataSelect=this.outputHeader.find("#dataSelector");this.outputTextArea.click(function(){this.select();console.log("click")});$("#insertSample").bind("click",function(g){g.preventDefault();b.insertSampleData();b.convert();_gaq.push(["_trackEvent","SampleData","InsertGeneric"])});$("#dataInput").keyup(function(){b.convert()});$("#dataInput").change(function(){b.convert();_gaq.push(["_trackEvent","DataType",b.outputDataType])});$("#dataSelector").bind("change",function(){b.outputDataType=$(this).val();
b.convert()});this.resize(c,i)};DataConverter.prototype.resize=function(c,i){var b=(i-90)/2-20;this.node.css({width:c});this.inputTextArea.css({width:c-20,height:b});this.outputTextArea.css({width:c-20,height:b})};
DataConverter.prototype.convert=function(){this.inputText=this.inputTextArea.val();this.outputText="";if(this.inputText.length>0){if(this.includeWhiteSpace===true)this.newLine="\n";else this.newLine=this.indent="";CSVParser.resetLog();var c=CSVParser.parse(this.inputText,this.headersProvided),i=c.errors;this.outputText=DataGridRenderer[this.outputDataType](c.dataGrid,c.headerNames,c.headerTypes,this.indent,this.newLine);this.outputTextArea.val(i+this.outputText)}};
DataConverter.prototype.insertSampleData=function(){this.inputTextArea.val('NAME\tVALUE\tCOLOR\tDATE\nAlan\t12\tblue\tSep. 25, 2009\nShan\t13\t"green\tblue"\tSep. 27, 2009\nJohn\t45\torange\tSep. 29, 2009\nMinna\t27\tteal\tSep. 30, 2009')};var widthOffset=345,heightOffset=35,d=new DataConverter("converter"),sidebar=$("#header"),win=$(window),w=win.width()-widthOffset,h=win.height()-heightOffset;d.create(w,h);$(".settingsElement").change(updateSettings);
$(window).bind("resize",function(){w=win.width()-widthOffset;h=win.height()-heightOffset;d.resize(w,h);sidebar.height(h)});
function updateSettings(c){var i=i||[];c&&i.push(["_trackEvent","Settings",c.currentTarget.id]);d.includeWhiteSpace=$("#includeWhiteSpaceCB").attr("checked");if(d.includeWhiteSpace){$("input[name=indentType]").removeAttr("disabled");c=$("input[name=indentType]:checked").val();if(c==="tabs")d.indent="\t";else if(c==="spaces")d.indent="  "}else $("input[name=indentType]").attr("disabled","disabled");d.headersProvided=$("#headersProvidedCB").attr("checked");if(d.headersProvided){$("input[name=headerModifications]").removeAttr("disabled");
c=$("input[name=headerModifications]:checked").val();if(c==="downcase"){d.downcaseHeaders=true;d.upcaseHeaders=false}else if(c==="upcase"){d.downcaseHeaders=false;d.upcaseHeaders=true}else if(c==="none"){d.downcaseHeaders=false;d.upcaseHeaders=false}}else $("input[name=headerModifications]").attr("disabled","disabled");d.useUnderscores=true;d.convert()}updateSettings();var CSVParser={isNumber:function(c){if(c==null||isNaN(new Number(c)))return false;return true},parse:function(c,i){var b=[];b=c.replace(RegExp("[^,]","gi"),"").length;var a=",";if(c.replace(RegExp("[^\t]","gi"),"").length>b)a="\t";c=c.replace(RegExp("^\n+","gi"),"");c=c.replace(RegExp("\n+$","gi"),"");b=this.CSVToArray(c,a);for(a=b.length-1;a>=0;a--)for(var e=b[a].length-1;e>=0;e--){b[a][e]=b[a][e].replace("\t","\\t");b[a][e]=b[a][e].replace("\n","\\n");b[a][e]=b[a][e].replace("\r","\\r")}e=[];var g=
[],l=b[0].length;if(i)e=b.splice(0,1)[0];else for(a=0;a<l;a++){e.push("val"+String(a));g.push("")}for(a=0;a<b.length;a++)b[a].length!=l&&this.log("Error parsing row "+String(a)+". Wrong number of columns.");for(a=0;a<e.length;a++){for(var j=0,f=0,k=0;k<l;k++)if(b[k])if(CSVParser.isNumber(b[k][a])){f++;String(b[k][a]).indexOf(".")>0&&j++}g[a]=f/l>0.5?j>0?"float":"int":"string"}return{dataGrid:b,headerNames:e,headerTypes:g,errors:this.getLog()}},errorLog:[],resetLog:function(){this.errorLog=[]},log:function(c){this.errorLog.push(c)},
getLog:function(){var c="";if(this.errorLog.length>0){for(var i=0;i<this.errorLog.length;i++)c+="!!"+this.errorLog[i]+"!!\n";c+="\n"}return c},CSVToArray:function(c,i){i=i||",";for(var b=RegExp("(\\"+i+'|\\r?\\n|\\r|^)(?:"([^"]*(?:""[^"]*)*)"|([^"\\'+i+"\\r\\n]*))","gi"),a=[[]],e=null;e=b.exec(c);){var g=e[1];g.length&&g!=i&&a.push([]);e=e[2]?e[2].replace(RegExp('""',"g"),'"'):e[3];a[a.length-1].push(e)}return a}};var DataGridRenderer={as:function(c,i,b,a,e){a="[";for(var g=c.length,l=i.length,j=0;j<g;j++){var f=c[j];a+="{";for(var k=0;k<l;k++){a+=i[k]+":"+(b[k]=="int"||b[k]=="float"?f[k]||"null":'"'+(f[k]||"")+'"');if(k<l-1)a+=","}a+="}";if(j<g-1)a+=","+e}a+="];";return a},asp:function(c,i,b,a,e){a="";var g=c.length;i=i.length;for(var l=0;l<g;l++)for(var j=c[l],f=0;f<i;f++)a+="myArray("+f+","+l+") = "+(b[f]=="int"||b[f]=="float"?j[f]||"null":'"'+(j[f]||"")+'"')+e;return"Dim myArray("+(f-1)+","+(l-1)+")"+e+
a},html:function(c,i,b,a,e){b="";var g=c.length,l=i.length;b+="<table>"+e;b+=a+"<thead>"+e;b+=a+a+"<tr>"+e;for(var j=0;j<l;j++){b+=a+a+a+'<th class="'+i[j]+'-cell">';b+=i[j];b+="</th>"+e}b+=a+a+"</tr>"+e;b+=a+"</thead>"+e;b+=a+"<tbody>"+e;for(var f=0;f<g;f++){var k=c[f];j="";if(f===g-1)j=' class="lastRow"';else if(f===0)j=' class="firstRow"';b+=a+a+"<tr"+j+">"+e;for(j=0;j<l;j++){b+=a+a+a+'<td class="'+i[j]+'-cell">';b+=k[j];b+="</td>"+e}b+=a+a+"</tr>"+e}b+=a+"</tbody>"+e;b+="</table>";return b},json:function(c,
i,b,a,e){a="[";for(var g=c.length,l=i.length,j=0;j<g;j++){var f=c[j];a+="{";for(var k=0;k<l;k++){a+='"'+i[k]+'":'+(b[k]=="int"||b[k]=="float"?f[k]||"null":'"'+(f[k]||"")+'"');if(k<l-1)a+=","}a+="}";if(j<g-1)a+=","+e}a+="];";return a},jsonArrayCols:function(c,i,b,a,e){var g="",l=c.length,j=i.length;g+="{"+e;for(var f=0;f<j;f++){g+=a+'"'+i[f]+'":[';for(var k=0;k<l;k++){g+=b[f]=="int"||b[f]=="float"?c[k][f]||0:'"'+(c[k][f]||"")+'"';if(k<l-1)g+=","}g+="]";if(f<j-1)g+=","+e}g+=e+"};";return g},jsonArrayRows:function(c,
i,b,a,e){var g="",l=c.length;i=i.length;g+="["+e;for(var j=0;j<l;j++){g+=a+"[";for(var f=0;f<i;f++){g+=b[f]=="int"||b[f]=="float"?c[j][f]||0:'"'+(c[j][f]||"")+'"';if(f<i-1)g+=","}g+="]";if(j<l-1)g+=","+e}g+=e+"];";return g},mysql:function(c,i,b,a,e){var g="",l=c.length,j=i.length;g+="CREATE TABLE MrDataConverter ("+e;g+=a+"id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,"+e;for(var f=0;f<j;f++){var k="VARCHAR(255)";if(b[f]=="int"||b[f]=="float")k=b[f].toUpperCase();g+=a+""+i[f]+" "+k;if(f<j-1)g+=",";g+=
e}g+=");"+e;g+="INSERT INTO MrDataConverter "+e+a+"(";for(f=0;f<j;f++){g+=i[f];if(f<j-1)g+=","}g+=") "+e+"VALUES "+e;for(i=0;i<l;i++){g+=a+"(";for(f=0;f<j;f++){g+=b[f]=="int"||b[f]=="float"?c[i][f]||"null":"'"+(c[i][f]||"")+"'";if(f<j-1)g+=","}g+=")";if(i<l-1)g+=","+e}g+=";";return g},php:function(c,i,b,a,e){var g="",l=c.length,j=i.length;g+="array("+e;for(var f=0;f<l;f++){var k=c[f];g+=a+"array(";for(var m=0;m<j;m++){g+='"'+i[m]+'"=>'+(b[m]=="int"||b[m]=="float"?k[m]||"null":'"'+(k[m]||"")+'"');
if(m<j-1)g+=","}g+=")";if(f<l-1)g+=","+e}g+=e+");";return g},python:function(c,i,b,a,e){a="[";for(var g=c.length,l=i.length,j=0;j<g;j++){var f=c[j];a+="{";for(var k=0;k<l;k++){a+='"'+i[k]+'":'+(b[k]=="int"||b[k]=="float"?f[k]||"None":'"'+(f[k]||"")+'"');if(k<l-1)a+=","}a+="}";if(j<g-1)a+=","+e}a+="];";return a},ruby:function(c,i,b,a,e){a="";var g=c.length,l=i.length;a+="[";for(var j=0;j<g;j++){var f=c[j];a+="{";for(var k=0;k<l;k++){a+='"'+i[k]+'"=>'+(b[k]=="int"||b[k]=="float"?f[k]||"nil":'"'+(f[k]||
"")+'"');if(k<l-1)a+=","}a+="}";if(j<g-1)a+=","+e}a+="];";return a},xml:function(c,i,b,a,e){b="";var g=c.length,l=i.length;b='<?xml version="1.0" encoding="UTF-8"?>'+e;b+="<rows>"+e;for(var j=0;j<g;j++){var f=c[j];b+=a+"<row>"+e;for(var k=0;k<l;k++){b+=a+a+"<"+i[k]+">";b+=f[k]||"";b+="</"+i[k]+">"+e}b+=a+"</row>"+e}b+="</rows>";return b},xmlProperties:function(c,i,b,a,e){b="";var g=c.length,l=i.length;b='<?xml version="1.0" encoding="UTF-8"?>'+e;b+="<rows>"+e;for(var j=0;j<g;j++){var f=c[j];b+=a+
"<row ";for(var k=0;k<l;k++){b+=i[k]+"=";b+='"'+f[k]+'" '}b+="></row>"+e}b+="</rows>";return b}};
